### PR TITLE
Basic Layout

### PR DESCRIPTION
**Pull request by Yugandhartripathi**
Added home page , about section and inter linked home , about , leaderboard.

### CODE REVIEW

**Comment by ryzokuken** [comment]
Add screenshots too.

**Comment by Yugandhartripathi** [comment]
http://prntscr.com/iveo52
http://prntscr.com/iveoby
http://prntscr.com/iveoh0
It needs a lot of work in styling department...
I don't know why leaderboard is not loading after I linked it to other pages

**Comment by saranshbarua** [comment]
hey, @Yugandhartripathi , it's nice that you started working on the website. I just wanted to know if you are working on the theme that is currently active, or are you implementing something on your own?

**Comment by Yugandhartripathi** [comment]
@saranshbarua Implementing design that i think will look good, I don't know about any general theme that we have to follow.

**Comment by saranshbarua** [comment]
Ok, I got the answer by looking at those screenshots. We don't need to reimplement the design, we just need to continue building from the current checkpoint. This time in React. It would be better if you take help from the previous code and implement it.

**Comment by Yugandhartripathi** [comment]
@saranshbarua Ok so we are making it same as old one but in gatsby this time. So like old one was scroll based single page model , we are gonna introduce links or leaderboard etc. goes down the scroll too like about section?

**Comment by saranshbarua** [comment]
I think we need to discuss that and see what other people think. @ryzokuken any suggestions?

**Comment by ryzokuken** [comment]
My call: different pages.

**Comment by Yugandhartripathi** [comment]
Let's move it to discord?

**Comment by saranshbarua** [comment]
Different pages for every section? We won't have much matter on the homepage then.

**Comment by Yugandhartripathi** [comment]
If we can pull certain data from github like no. of commits in leaderboard , we can make some stats display on the home page like...total number of commits by osdc or no. Of members or number of active projects etc assuming the data fetching via octokit/rest is dynamic

**Comment by ryzokuken** [comment]
Then let's make new pages for dynamic content only?

**Comment by ryzokuken** [comment]
> assuming the data fetching via octokit/rest is dynamic

It is.

**Comment by ryzokuken** [comment]
Regarding the current look, it looks alright but could do much better. Idk, on second thought the alcohol theme doesn't look too good and we should *probably* drop it.

**Comment by saranshbarua** [comment]
@ryzokuken I remember everyone agreed on it, that's why we made it. It looks completely fine to me unless you bring your *moral* values in the game

**Comment by ryzokuken** [comment]
I remember myself being the one that proposed it in the first place, I'm just saying that it didn't turn out as cool as expected. Again, it looks totally good though.

**Comment by ryzokuken** [comment]
@saranshbarua ping.

**Comment by saranshbarua** [comment]
@Yugandhartripathi Since I integrated the previous website on Gatsby with proper styles, I think we don't need this now. You can continue from current checkpoint. Closing this for now.

**Pull request closed without merging**
