### PR TITLE
Updated dependencies

### PR DESCRIPTION
**Pull request by sidntrivedi**
/cc: @ryzokuken @saranshbarua

### CODE REVIEW

**Comment by sidntrivedi** [comment]
Oops. Missed that we use yarn here. Pushing changes again.

**Comment by saranshbarua** [comment]
@sidntrivedi012 make sure that the build is working properly after this. Also, please squash the commits.

**Comment by sidntrivedi** [comment]
@saranshbarua Yes, it is building without any issues. Also, running fine in development.
osdc-site

**Comment by sidntrivedi** [comment]
Also, can you please squash the commits while merging through the Merge button? It's relatively easier as compared to the CLI version 😅

**Comment by sidntrivedi** [comment]
Deployed.

**Pull request merged**
