### PR TITLE
I added a fade in transition for OSDC logo on landing page

### PR DESCRIPTION
**Pull request by code-monk08**

### CODE REVIEW

**Comment by code-monk08** [comment]
Please Review..

**Comment by HarendraSingh22** [comment]
Sir Like , how could I add a review and  suggest change in a repo I am in no way related to? Can just any random person review codes in any public repository?

**Comment by ryzokuken** [comment]
@HarendraSingh22 that's the beauty of open source. Anyone can review pull requests, and make their thoughts heard. As long as you are making valid arguments, chances are, both the maintainer and the assignee will listen to you. Infact, community peer-review is so good, services like http://www.pullrequestroulette.com/ are very popular among us developers.

**Comment by 526avijitgupta** [comment]
@code-monk08 Any updates on this ?

**Comment by code-monk08** [comment]
@526avijitgupta Sir, I tried updating the code but I realized that fading effect was not coming out as it was supposed to come..!

**Comment by ryzokuken** [comment]
@code-monk08 closing this for now. Let us know when you want this to be reopened or just make a new PR when you're ready. Thanks.

**Pull request closed without merging**
