### PR TITLE
adjust fonts to make text more readable

### PR DESCRIPTION
**Pull request by saranshbarua**
screen shot 2018-10-27 at 11 50 35 pm

### CODE REVIEW

**Comment by ryzokuken** [comment]
I was going to reject this PR, but you didn't wait for review.

**Comment by saranshbarua** [comment]
@ryzokuken is there something wrong?

**Comment by ryzokuken** [comment]
It's perfect. Just... try not to make PRs from your `master` branch. I wanted to force you into a good habit.

**Comment by saranshbarua** [comment]
Oh didn't notice I have a source branch too. My bad. Will keep this in mind for future PR's :)

**Comment by ryzokuken** [comment]
😉

**Pull request merged**
