### PR TITLE
Integrate previous site with gatsby

### PR DESCRIPTION
**Pull request by saranshbarua**
I merged the last site into Gatsby. I removed the beer glass(for some moral reasons). And the down-arrow is removed for now. I need people to build this further.

### CODE REVIEW

**Review by ryzokuken — CHANGES_REQUESTED** [review]
We don't need the html, css, or the font files. Please remove them.

**Comment by saranshbarua** [comment]
@ryzokuken I removed the index.html as well as css files. Can you help me with the font files and implement a work-around?

**Review by ryzokuken — APPROVED** [review]
@saranshbarua LGTM. Shall I merge and deploy?

**Comment by ryzokuken** [comment]
@saranshbarua we could add font files later if they work RN.

**Comment by saranshbarua** [comment]
Sure.

**Comment by ryzokuken** [comment]
So, should I merge?

**Comment by saranshbarua** [comment]
@ryzokuken yes!

**Comment by ryzokuken** [comment]
Merged! 🎉

**Pull request merged**
