### PR TITLE
Removed files

### PR DESCRIPTION
**Pull request by ojasbansal**

### CODE REVIEW

**Comment by yashmehrotra** [comment]
Hi, thanks for the commit. Kindly do the following:

1. Squash your commits into one.
2. Use correct indentation where ever required.
3. Better description for the pull request.

@526avijitgupta @ryzokuken Kindly verify the directory structure. Also, are the complete JS files required for the functionality, or can something be trimmed down.

**Comment by 526avijitgupta** [comment]
@ojas1234 Any updates ?

**Comment by ojas1234** [comment]
@526avijitgupta I had try to squash commits but it not worked and also googled it but find no help.
@ryzokuken He said that he already pushed the changes for full page. So i don't go for it.

**Comment by ryzokuken** [comment]
@ojas1234 closing this as the context has shifted. Looking forward to see you work on this iteration of the website as well.

**Pull request closed without merging**
