### PR TITLE
add smooth scrolling action for arrowdown button

### PR DESCRIPTION
**Pull request by saranshbarua**
[Preview](https://saranshbarua.github.io/osdc.github.io/)

### CODE REVIEW

**Comment by yashmehrotra** [comment]
Would be better if script is downloaded from CDN and its minified

**Comment by 526avijitgupta** [comment]
@saranshbarua Simply use this: https://cdnjs.cloudflare.com/ajax/libs/smooth-scroll/11.1.0/js/smooth-scroll.min.js

**Comment by saranshbarua** [comment]
I did the changes.

**Comment by yashmehrotra** [comment]
LGTM

**Pull request merged**
